### ISSUE TITLE
Does deviation decay passively?

### ISSUE THREAD

**Issue by Tarquinous** [halvnykterist/rating-update#13]
In a recent discussion someone raised that their rating deviation across the span of 3 days appeared to become more uncertain, despite no additional games being played. This raised the question if there is deviation decay, which isn't mentioned anywhere on the website.

**Comment by halvnykterist** [comment]
Yes, this is a feature of the glicko rating system used. I'll add a FAQ entry for it.

**Comment by halvnykterist** [comment]
FAQ entry added!
