### ISSUE TITLE
Percentile calculation goes above 100%

### ISSUE THREAD

**Issue by TaleOfFriendship** [halvnykterist/rating-update#16]
The website shows percentiles above 100% for the very top players. This happened relatively recently I think.

![AZTBliU - Imgur](https://user-images.githubusercontent.com/28742479/165348201-d131b943-f5cc-42fc-9fce-3fb9e4087072.png)
)

**Comment by TaleOfFriendship** [comment]
I don't mind taking a quick look at the source code. Is there a script in the repo where this number is being calculated?

**Comment by halvnykterist** [comment]
I looked into it a bit, I think what's causing the problem the percentiles are being calculated relative to the current population while the counts are based on the population when it was calculated. Think I have a fix.

**Comment by halvnykterist** [comment]
Fixed, I think!
