### ISSUE TITLE
Order Top Players by their rating instead of lower bound of their rating

### ISSUE THREAD

**Issue by TaleOfFriendship** [halvnykterist/rating-update#17]
Hello,

love your site. Have some possible input:

The Top players are ordered by the lower bound of the rating with regard to uncertainty. 
For example Rank 9 vs rank 10 in this picture:

![2022-04-26 19_44_33-Window](https://user-images.githubusercontent.com/28742479/165360796-fe9938de-b71e-40c8-922d-c682d95d8e29.png)

Rank 9 is higher ranked with a rating of 2241 than rank 10, who has a rating of 2257.

I imagine this is intentional, but for me ordering it like this is not very intuitive and I would order the rating by the expected number, i.e.  rank 10 should be above rank 9. What do you think?

**Comment by halvnykterist** [comment]
You're right that this is intentional. Initially this was based off of the thought that bounds would be wider but now that people mostly are in the same range it might be worth changing.

There's also the "feel-good" aspect if your rank going up as your deviation goes down, but I don't know how much I care about that anyway.

**Comment by TaleOfFriendship** [comment]
I agree that the current approach has some advantages, especially to avoid having very high variance ratings show up at the top.
Since you limit the top ranks to 150 variance I think that is not too much of an issue. 

At the moment the list is ordered by an "invisible" column that is not shown in the list (Expected value - variance), which is unorthodox for a Top list, so I think an alternative solution is a new column with lower bound so people can see why the list is ordered this way. For me personally, I use your site often and mainly care about the expected value so I would still order by that.

**Comment by jfeversole** [comment]
@halvnykterist Is this pending implementation+PR or is this pending a decision on whether or not to move forward?

**Comment by halvnykterist** [comment]
> @halvnykterist Is this pending implementation+PR or is this pending a decision on whether or not to move forward?

Pending decision, the actual implementation is trivial (just swapping `ORDER BY value - 2 * deviation DESC` for `ORDER BY value DESC` in the ranking query).

I'll try and remember today to export two versions of the top 100 with and without this to see if it changes anything significantly. I think my primary concern is that you'd get a lot more "jitter" with lower game count players entering the leaderboards with unstable ratings.

**Comment by halvnykterist** [comment]
Big tables incoming

### Current ranking algorithm:

| Rank | Name | Character | Rating | Games |
|------|------|-----------|--------|-------|
| 1 | June 10th | Happy Chaos | 2306 ±85 | 4935 (70%) |
| 2 | June 10th | Happy Chaos | 2305 ±91 | 4204 (78%) |
| 3 | NBNHMR | Nagoriyuki | 2270 ±78 | 9255 (86%) |
| 4 | Darkrai | Goldlewis | 2259 ±73 | 11698 (91%) |
| 5 | NASR \| Latif | Zato-1 | 2293 ±110 | 6823 (82%) |
| 6 | UMVC3 Player | Happy Chaos | 2262 ±83 | 8338 (86%) |
| 7 | June 10th | May | 2222 ±98 | 1759 (59%) |
| 8 | tatuFa | Sol | 2188 ±69 | 3624 (76%) |
| 9 | ONi DarkNecro | Nagoriyuki | 2221 ±104 | 3309 (88%) |
| 10 | June 10th | Ramlethal | 2173 ±57 | 3064 (70%) |
| 11 | PaiDosLeiteiros | Goldlewis | 2165 ±52 | 8399 (85%) |
| 12 | Verix777 | Nagoriyuki | 2192 ±80 | 5024 (73%) |
| 13 | Hybrid | Sol | 2257 ±145 | 939 (81%) |
| 14 | 竹原 | Ramlethal | 2204 ±92 | 574 (64%) |
| 15 | GG PLAYER | Zato-1 | 2192 ±88 | 3113 (91%) |
| 16 | Tim119 | Giovanna | 2180 ±82 | 3093 (82%) |
| 17 | june 10th  | Leo | 2212 ±117 | 274 (75%) |
| 18 | ZENO ZENO ZENO Z | Happy Chaos | 2169 ±76 | 2770 (75%) |
| 19 | June 10th | Happy Chaos | 2175 ±88 | 3347 (83%) |
| 20 | June 10th | Leo | 2174 ±88 | 513 (83%) |
| 21 | †キリトloveアスナ† | Potemkin | 2145 ±64 | 1655 (88%) |
| 22 | Daru_I-No | I-No | 2178 ±99 | 2705 (83%) |
| 23 | Lament | May | 2149 ±70 | 6185 (78%) |
| 24 | Solar | Axl | 2185 ±109 | 3174 (80%) |
| 25 | Acnologio | Giovanna | 2138 ±65 | 6338 (63%) |
| 26 | 下水 | Leo | 2186 ±116 | 3026 (89%) |
| 27 | ZIN | Chipp | 2130 ±64 | 4633 (77%) |
| 28 | JSP FANBOY | Leo | 2153 ±89 | 2190 (66%) |
| 29 | June 10th | Happy Chaos | 2197 ±134 | 1423 (81%) |
| 30 | 妹好きPlayer | Happy Chaos | 2140 ±80 | 4515 (77%) |
| 31 | June 10th | Chipp | 2197 ±143 | 1691 (85%) |
| 32 | Elo Eddie | Zato-1 | 2138 ±88 | 368 (60%) |
| 33 | kouhide | Giovanna | 2118 ±69 | 8914 (84%) |
| 34 | Snake Eyez | Potemkin | 2114 ±65 | 5710 (86%) |
| 35 | KantoKinte | Sol | 2161 ±114 | 1729 (74%) |
| 36 | June 10th | Chipp | 2187 ±143 | 780 (85%) |
| 37 | Rat | Millia | 2149 ±105 | 3938 (70%) |
| 38 | Romolla | Sol | 2179 ±138 | 100 (75%) |
| 39 | June 10th | Chipp | 2173 ±134 | 1324 (88%) |
| 40 | Zippy | Ky | 2115 ±77 | 3581 (76%) |
| 41 | Solstice | Ramlethal | 2169 ±131 | 1054 (87%) |
| 42 | Budfelic | Nagoriyuki | 2100 ±63 | 3749 (81%) |
| 43 | KantoKinte | Axl | 2112 ±75 | 1686 (74%) |
| 44 | RemiCeleste | Axl | 2181 ±145 | 683 (77%) |
| 45 | June 10th | Chipp | 2151 ±118 | 1295 (85%) |
| 46 | Kreeg | Happy Chaos | 2097 ±64 | 2962 (77%) |
| 47 | WAIT IS EU FREE | Happy Chaos | 2162 ±130 | 2077 (84%) |
| 48 | 김락봉 | Ramlethal | 2144 ±112 | 1995 (77%) |
| 49 | SQ | Ramlethal | 2128 ±97 | 2373 (82%) |
| 50 | Fame96 | Nagoriyuki | 2156 ±125 | 232 (65%) |
| 51 | sanakan | Happy Chaos | 2118 ±88 | 2689 (84%) |
| 52 | Bean | Chipp | 2133 ±103 | 1035 (79%) |
| 53 | June 10th | Chipp | 2164 ±136 | 1899 (84%) |
| 54 | Tee | Chipp | 2108 ±80 | 2730 (83%) |
| 55 | Kwiddo | Ramlethal | 2136 ±109 | 3734 (74%) |
| 56 | Falkor | May | 2115 ±88 | 5207 (67%) |
| 57 | June 10th | Chipp | 2146 ±120 | 427 (89%) |
| 58 | UMVC3 Player | Leo | 2102 ±79 | 356 (79%) |
| 59 | Moist \| Hotashi | Nagoriyuki | 2120 ±98 | 4473 (79%) |
| 60 | Arrow | Potemkin | 2112 ±91 | 6813 (84%) |
| 61 | ティーワイ | Giovanna | 2160 ±140 | 1121 (87%) |
| 62 | forgotten frank | Ramlethal | 2111 ±92 | 2482 (79%) |
| 63 | tkrnsan | Axl | 2115 ±97 | 3014 (81%) |
| 64 | June 10th | Chipp | 2124 ±106 | 912 (85%) |
| 65 | JSP FANBOY | Axl | 2124 ±110 | 492 (66%) |
| 66 | June 10th | Chipp | 2106 ±94 | 1040 (80%) |
| 67 | Zimpery | Faust | 2068 ±58 | 10611 (80%) |
| 68 | Alter | Sol | 2121 ±112 | 923 (87%) |
| 69 | Hazard | Chipp | 2123 ±116 | 3352 (49%) |
| 70 | Dunktrain23.ttv | Nagoriyuki | 2074 ±71 | 8212 (82%) |
| 71 | TestYourLuck | Nagoriyuki | 2109 ±108 | 3388 (82%) |
| 72 | MORBIUSFAN53 | Happy Chaos | 2075 ±77 | 473 (56%) |
| 73 | ごーやーまん | I-No | 2080 ±83 | 8567 (83%) |
| 74 | ベアラス | Millia | 2071 ±75 | 817 (82%) |
| 75 | FGCMachoPC | Zato-1 | 2092 ±97 | 1151 (85%) |
| 76 | Bean | Leo | 2143 ±147 | 999 (80%) |
| 77 | Washed Willy | Zato-1 | 2085 ±90 | 5609 (69%) |
| 78 | Bex_jp | Sol | 2063 ±69 | 5344 (81%) |
| 79 | wiggins#1fanNA | Ky | 2094 ±102 | 2874 (78%) |
| 80 | YWNBAW | Ky | 2080 ±90 | 2327 (85%) |
| 81 | GG Player | Axl | 2119 ±131 | 2485 (79%) |
| 82 | name123 | Zato-1 | 2056 ±68 | 6955 (74%) |
| 83 | BIG TONKA T | Sol | 2070 ±84 | 989 (79%) |
| 84 | GenisGod | Ramlethal | 2057 ±71 | 3016 (75%) |
| 85 | Kinuski | Baiken | 2047 ±62 | 5057 (78%) |
| 86 | Togata | Zato-1 | 2077 ±94 | 2562 (71%) |
| 87 | doram | Ramlethal | 2080 ±97 | 3268 (77%) |
| 88 | Pochi The Dog | Axl | 2060 ±78 | 5572 (80%) |
| 89 | 06/10 ur cooked | Sol | 2066 ±84 | 2534 (80%) |
| 90 | SweetWind | Chipp | 2050 ±70 | 6213 (80%) |
| 91 | キコノヨ | Happy Chaos | 2069 ±89 | 4399 (63%) |
| 92 | Setchi | Zato-1 | 2097 ±119 | 1017 (76%) |
| 93 | まーりんぱ〇 | Zato-1 | 2072 ±96 | 3596 (80%) |
| 94 | Armix | Ramlethal | 2062 ±85 | 1178 (62%) |
| 95 | Zakotou | Ky | 2041 ±65 | 2898 (79%) |
| 96 | ikushisu | Ramlethal | 2069 ±95 | 3983 (76%) |
| 97 | BedlessSleeper | Goldlewis | 2066 ±92 | 4660 (76%) |
| 98 | bela | May | 2048 ±76 | 1671 (64%) |
| 99 | sanakan | Nagoriyuki | 2114 ±142 | 1167 (84%) |
| 100 | SugoiBoi | Millia | 2055 ±84 | 2270 (77%) |

### Ignoring deviation:

| Rank | Name | Character | Rating | Games |
|------|------|-----------|--------|-------|
| 1 | June 10th | Happy Chaos | 2306 ±85 | 4935 (70%) |
| 2 | June 10th | Happy Chaos | 2305 ±91 | 4204 (78%) |
| 3 | NASR \| Latif | Zato-1 | 2293 ±110 | 6823 (82%) |
| 4 | NBNHMR | Nagoriyuki | 2270 ±78 | 9255 (86%) |
| 5 | UMVC3 Player | Happy Chaos | 2262 ±83 | 8338 (86%) |
| 6 | Hybrid | Sol | 2257 ±145 | 939 (81%) |
| 7 | Darkrai | Goldlewis | 2257 ±73 | 11697 (91%) |
| 8 | June 10th | May | 2222 ±98 | 1759 (59%) |
| 9 | ONi DarkNecro | Nagoriyuki | 2221 ±104 | 3309 (88%) |
| 10 | june 10th  | Leo | 2212 ±117 | 274 (75%) |
| 11 | 竹原 | Ramlethal | 2204 ±92 | 574 (64%) |
| 12 | June 10th | Chipp | 2197 ±143 | 1691 (85%) |
| 13 | June 10th | Happy Chaos | 2197 ±134 | 1423 (81%) |
| 14 | Verix777 | Nagoriyuki | 2192 ±80 | 5024 (73%) |
| 15 | GG PLAYER | Zato-1 | 2192 ±88 | 3113 (91%) |
| 16 | tatuma | Sol | 2188 ±69 | 3624 (76%) |
| 17 | June 10th | Chipp | 2187 ±143 | 780 (85%) |
| 18 | 下水 | Leo | 2186 ±116 | 3026 (89%) |
| 19 | Solar | Axl | 2185 ±109 | 3174 (80%) |
| 20 | RemiCeleste | Axl | 2181 ±145 | 683 (77%) |
| 21 | Tim119 | Giovanna | 2180 ±82 | 3093 (82%) |
| 22 | Romolla | Sol | 2179 ±138 | 100 (75%) |
| 23 | Daru_I-No | I-No | 2178 ±99 | 2705 (83%) |
| 24 | June 10th | Happy Chaos | 2175 ±88 | 3347 (83%) |
| 25 | June 10th | Leo | 2174 ±88 | 513 (83%) |
| 26 | June 10th | Ramlethal | 2173 ±57 | 3064 (70%) |
| 27 | June 10th | Chipp | 2173 ±134 | 1324 (88%) |
| 28 | Solstice | Ramlethal | 2169 ±131 | 1054 (87%) |
| 29 | ZENO ZENO ZENO Z | Happy Chaos | 2169 ±76 | 2770 (75%) |
| 30 | PaiDosLeiteiros | Goldlewis | 2165 ±52 | 8399 (85%) |
| 31 | June 10th | Chipp | 2164 ±136 | 1899 (84%) |
| 32 | WAIT IS EU FREE | Happy Chaos | 2162 ±130 | 2077 (84%) |
| 33 | KantoKinte | Sol | 2161 ±114 | 1729 (74%) |
| 34 | ティーワイ | Giovanna | 2160 ±140 | 1121 (87%) |
| 35 | Fame96 | Nagoriyuki | 2156 ±125 | 232 (65%) |
| 36 | JSP FANBOY | Leo | 2153 ±89 | 2190 (66%) |
| 37 | June 10th | Chipp | 2151 ±118 | 1295 (85%) |
| 38 | Rat | Millia | 2149 ±105 | 3938 (70%) |
| 39 | Lament | May | 2149 ±70 | 6185 (78%) |
| 40 | June 10th | Chipp | 2146 ±120 | 427 (89%) |
| 41 | †キリトloveアスナ† | Potemkin | 2145 ±64 | 1655 (88%) |
| 42 | 김락봉 | Ramlethal | 2144 ±112 | 1995 (77%) |
| 43 | Bean | Leo | 2143 ±147 | 999 (80%) |
| 44 | 妹好きPlayer | Happy Chaos | 2140 ±80 | 4515 (77%) |
| 45 | Elo Eddie | Zato-1 | 2138 ±88 | 368 (60%) |
| 46 | Acnologio | Giovanna | 2138 ±65 | 6338 (63%) |
| 47 | Kwiddo | Ramlethal | 2136 ±109 | 3734 (74%) |
| 48 | Bean | Chipp | 2133 ±103 | 1035 (79%) |
| 49 | ZIN | Chipp | 2130 ±64 | 4633 (77%) |
| 50 | SQ | Ramlethal | 2128 ±97 | 2373 (82%) |
| 51 | June 10th | Chipp | 2124 ±106 | 912 (85%) |
| 52 | JSP FANBOY | Axl | 2124 ±110 | 492 (66%) |
| 53 | Hazard | Chipp | 2123 ±116 | 3352 (49%) |
| 54 | Alter | Sol | 2121 ±112 | 923 (87%) |
| 55 | Moist \| Hotashi | Nagoriyuki | 2120 ±98 | 4473 (79%) |
| 56 | GG Player | Axl | 2119 ±131 | 2485 (79%) |
| 57 | kouhide | Giovanna | 2118 ±69 | 8914 (84%) |
| 58 | sanakan | Happy Chaos | 2118 ±88 | 2689 (84%) |
| 59 | Zippy | Ky | 2115 ±77 | 3581 (76%) |
| 60 | tkrnsan | Axl | 2115 ±97 | 3014 (81%) |
| 61 | Falkor | May | 2115 ±88 | 5207 (67%) |
| 62 | sanakan | Nagoriyuki | 2114 ±142 | 1167 (84%) |
| 63 | Snake Eyez | Potemkin | 2114 ±65 | 5710 (86%) |
| 64 | KantoKinte | Axl | 2112 ±75 | 1686 (74%) |
| 65 | Arrow | Potemkin | 2112 ±91 | 6813 (84%) |
| 66 | forgotten frank | Ramlethal | 2111 ±92 | 2482 (79%) |
| 67 | TestYourLuck | Nagoriyuki | 2109 ±108 | 3388 (82%) |
| 68 | Tee | Chipp | 2108 ±80 | 2730 (83%) |
| 69 | Nerf \| 9m Shine | Potemkin | 2108 ±139 | 1159 (86%) |
| 70 | June 10th | Chipp | 2106 ±94 | 1040 (80%) |
| 71 | UMVC3 Player | Leo | 2102 ±79 | 356 (79%) |
| 72 | れれ | Sol | 2102 ±138 | 5496 (77%) |
| 73 | Budfelic | Nagoriyuki | 2100 ±63 | 3749 (81%) |
| 74 | ttv Diaphone_ | I-No | 2098 ±135 | 444 (82%) |
| 75 | Kreeg | Happy Chaos | 2097 ±64 | 2962 (77%) |
| 76 | Setchi | Zato-1 | 2097 ±119 | 1017 (76%) |
| 77 | wiggins#1fanNA | Ky | 2094 ±102 | 2874 (78%) |
| 78 | STE\|ジロー | Anji | 2093 ±148 | 547 (80%) |
| 79 | FGCMachoPC | Zato-1 | 2092 ±97 | 1151 (85%) |
| 80 | early_type | Chipp | 2088 ±147 | 140 (81%) |
| 81 | Washed Willy | Zato-1 | 2085 ±90 | 5609 (69%) |
| 82 | AsuraSwagDaddy | Sol | 2083 ±142 | 927 (74%) |
| 83 | ごーやーまん | I-No | 2080 ±83 | 8567 (83%) |
| 84 | YWNBAW | Ky | 2080 ±90 | 2327 (85%) |
| 85 | doram | Ramlethal | 2080 ±97 | 3268 (77%) |
| 86 | brkrdv | Giovanna | 2079 ±114 | 1406 (73%) |
| 87 | Togata | Zato-1 | 2077 ±94 | 2562 (71%) |
| 88 | FG \| Marvelo | Chipp | 2077 ±109 | 360 (78%) |
| 89 | MORBIUSFAN53 | Happy Chaos | 2075 ±77 | 473 (56%) |
| 90 | Dunktrain23.ttv | Nagoriyuki | 2074 ±71 | 8212 (82%) |
| 91 | BarfyCrayon | Giovanna | 2073 ±117 | 7326 (74%) |
| 92 | まーりんぱ〇 | Zato-1 | 2072 ±96 | 3596 (80%) |
| 93 | VilkaShekotki | Chipp | 2071 ±149 | 1866 (77%) |
| 94 | ベアラス | Millia | 2071 ±75 | 817 (82%) |
| 95 | ベアラス | Baiken | 2071 ±102 | 528 (81%) |
| 96 | BIG TONKA T | Sol | 2070 ±84 | 989 (79%) |
| 97 | ikushisu | Ramlethal | 2069 ±95 | 3983 (76%) |
| 98 | キコノヨ | Happy Chaos | 2069 ±89 | 4399 (63%) |
| 99 | June 10th | Baiken | 2068 ±113 | 1067 (67%) |
| 100 | Zimpery | Faust | 2068 ±58 | 10611 (80%) |


Overall there doesn't seem to be that much of a difference, most of the high deviation names I looked at in the raw ranked version were top 200 normally anyway. I'd be happy to see someone else take a look and point out any unfairness I've missed.

**Comment by jfeversole** [comment]
Not OP, but I'm on the same page as you. I wanted to offer knocking this out if this was just needing a quick PR, but it sounds like it can be closed.

**Comment by halvnykterist** [comment]
Yep, I implemented it a few days ago but must have forgotten to close the issue. Really didn't change too much but made the main page easier to follow. Will close it now.
