### ISSUE TITLE
`/api/player_rating/` returns float rating

### ISSUE THREAD

**Issue by optix2000** [halvnykterist/rating-update#19]
Been poking around about how to inject ratings in totsugeki.

http://ratingupdate.info/api/player_rating/2ED5D216E0E9414/ZA
returns
```
{"value":5.110550664616985,"deviation":0.2068578102309275,"volatility":0.020502236249574934}
```

How can I convert this to the 1500-normalized rating? (eg 2388 ±72)

**Comment by halvnykterist** [comment]
Sorry I didn't notice this before! The conversion scale is multiplying by 173 and adding 1500. For deviation it's multiplied by 2 * 173.

However, there's a pretty big update in the pipeline that'll switch the website to be natively using the Glicko-1 scale, so once that's released this API path will return ratings in the same scale as the website (although deviations will still have to be doubled to show 95% confidence)

**Comment by halvnykterist** [comment]
That new update is out! You'll still need to multiply deviation by 2 if you want to match what's shown on the website, but the multiplier is gone.

**Comment by optix2000** [comment]
Noice. I'll shoot you a build of totsugeki in the next week or so with the ratings working.
