### ISSUE TITLE
Tables empty after running cargo run -- update

### ISSUE THREAD

**Issue by TaleOfFriendship** [halvnykterist/rating-update#20]
Hello,

I am trying to get the database running locally but some tables stay empty.

After running cargo run -- pull twice I got some entries in the tables 'games' and 'players' just fine.
![image](https://user-images.githubusercontent.com/28742479/168450443-dafa92d7-c3c7-4d08-9ae6-b161a2e09efd.png)
![image](https://user-images.githubusercontent.com/28742479/168450487-fdabb9a2-7224-4d44-a01a-3e09c4d8e78b.png)

Then I run cargo run -- update:
![image](https://user-images.githubusercontent.com/28742479/168450434-e264b2aa-4058-4c98-ac10-30598a60a7f5.png)

But all tables aside from games and players stay empty (for example global_matchup):
![image](https://user-images.githubusercontent.com/28742479/168450527-0db35c79-d67f-43d3-9104-818fefd1d075.png)

Do you have an idea of what it could be?

**Comment by halvnykterist** [comment]
If you don't  have that many games yet, it might be partially a problem with uncertainty. The site requires a deviation under a limit before adding results to those charts.  After you've gotten the rating engine "up to speed" new players get correct low deviation ratings pretty quickly, but the first few thousands of games have people moving a lot slower.

**Comment by TaleOfFriendship** [comment]
I think you are right. After having around 60k games in the DB the tables started getting populated. Fraud Index is still empty but the way these numbers are calculated I imagine I need even more games for them.
