### ISSUE TITLE
Where do player ID's come from?

### ISSUE THREAD

**Issue by optix2000** [halvnykterist/rating-update#22]
Given a player URL: http://ratingupdate.info/player/30E051CA9272A58/HA

Where does the player ID come from (ie `2ED5D216E0E9414`)?
GGST uses numerical player ID's, as does Steam.

**Comment by halvnykterist** [comment]
Those are a hex representation of an R-code ID. I believe these aren't visible in game, the ones strive shows on PC are steam IDs.

**Comment by optix2000** [comment]
Got it. Thanks!
