### ISSUE TITLE
API to get ratings of all characters

### ISSUE THREAD

**Issue by optix2000** [halvnykterist/rating-update#23]
Currently fetching ratings through Totsugeki takes quite some time (about 9 seconds from US West), as each character's rating needs to be fetched independently.

Within Totsugeki, it's not possible to detect which character the opponent is playing, as matchmaking just requests all character stats, so totsugeki needs to fetch all character ratings.

Would be helpful to have an API call that gives all character ratings in a single request. eg `http://ratingupdate.info/api/player_rating/2ED5D216E0E9414`.

For Totsugeki specifically, I don't need the deviation as I can't display it anyways, but it can be included for other uses.

**Comment by halvnykterist** [comment]
Yep, that sounds good. I should be able to add that quickly.

What would be the most useful format for character IDs? Just the numeric version?

**Comment by optix2000** [comment]
I can already convert between numeric and hex player ID's so whatever is easier for you.

**Comment by halvnykterist** [comment]
Ah, I meant for the character IDs, would you prefer `0: 1234.5678` or `"SO":`?
Could even make it an array of all possible characters with the missing ones just set to 1500

**Comment by halvnykterist** [comment]
It's up now, ended up doing an array of all possible characters that's populated by either default ratings (which is what your rating is if you "don't have one" or ratings for those characters.

http://ratingupdate.info/api/player_rating/2ED5D216E0E9414

**Comment by optix2000** [comment]
Works perfectly!

Here's the initial version. https://github.com/optix2000/totsugeki/releases/tag/v1.9.1-rating-update
