### ISSUE TITLE
Characters missing on player page matchup table

### ISSUE THREAD

**Issue by saskaak** [halvnykterist/rating-update#24]
On my page the matchup table is missing chipp and leo, even though I *have* played against both after the season reset.

http://console.ratingupdate.info/player/2EC3BE1ADFB2702/KY

![59F57C38-51D7-4889-871C-33865D7689E4](https://user-images.githubusercontent.com/44642427/173419401-7da19e25-45b0-4d7c-8e0f-51c93cf29b41.jpeg)

**Comment by halvnykterist** [comment]
Interesting - looks like the only Leos/Chipps you've fought against have been >150 deviation, so it's probably (erroneously) filtering on that.
