### ISSUE TITLE
Adding "private" profiles

### ISSUE THREAD

**Issue by Easy-Size** [halvnykterist/rating-update#25]
Hi, love the project. 

One thing I'm wondering about is if it's possible to keep a profile "private" or stop displaying rating changes. In-game, you are able to set your R-code to private, but as far as I'm aware that doesn't stop rating-update from tracking your games. 

For me personally I don't want people to be seeing all my activity, who/when I play etc.

**Comment by halvnykterist** [comment]
This feature already exists! Just give me your profile and I'll be able to mark it as hidden, it'll stop showing up in leaderboards and just be shown as `(Hidden)` in other players' histories. Your profile page also become inaccessible.
