### ISSUE TITLE
Can't start up website

### ISSUE THREAD

**Issue by Michiocre** [halvnykterist/rating-update#43]
When i start up the website using the command `cargo run` i get the following error:
```16:23:16 [INFO] Grabbing replays
16:23:16 [WARN] Grabbing steam token
thread 'tokio-runtime-worker' panicked at D:\Projects\rating-update\src\requests.rs:124:43:
called `Result::unwrap()` on an `Err` value: InitFailed
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
task 12 panicked
error: process didn't exit successfully: `target\debug\rating-update.exe` (exit code: 1)
```

It seems to be an issue with getting the Steam token but i cant figure out what the problem is.

**Comment by Michiocre** [comment]
I've figured out how to get at least this part working.
To fix the steam API error you have to add a file called `steam_appid.txt` with the content `1384160`.
This tells the steam API the app id of GGST.

Now i am stuck on a new problem.
Getting the GGST token always fails.
```
18:07:02 [INFO] Waiting for strive token
18:07:02 [ERROR] Error in received msgpack!

18:07:02 [ERROR] Error fetching replays: Couldn't get strive token
```

**Comment by Michiocre** [comment]
I tried adding the file that gets generated by `generate_steam_token.py` and changing the content of `steam_token.txt`.
That didnt change anything.

**Comment by hunterloftus** [comment]
Hey Michiocre,

I'm having the exact same issues and was able to replicate everything you've done. Were you ever able to fix the issue you were having?

**Comment by Michiocre** [comment]
No i tried a few other things but i couldnt get it to work.
You could check #38 to see if any of the things there could help you.

**Comment by Michiocre** [comment]
I recently pulled the new Version on my fork, and now i am able to make it past the login stage.
So i get the `Strive Token`

No wit just fails at getting the replays.
```
15:24:46 [DEBUG] (1) reqwest::connect: starting new connection: https://ggst-game.guiltygear.com/
15:24:48 [INFO] Waiting for strive token
15:24:48 [INFO] Got token: MY_TOKEN_HERE
15:24:48 [INFO] Grabbing replays (page 0)
15:24:48 [DEBUG] (1) reqwest::connect: starting new connection: https://ggst-game.guiltygear.com/
15:24:49 [ERROR] Error in received msgpack!

15:24:49 [ERROR] Error fetching replays: Couldn't load replays
```

When i convert the recieved message from hex to a string it also looks pretty much identical to the one mentioned in #38.

Still have no clue where to go from here tho.

**Comment by Michiocre** [comment]
@hunterloftus 
I was giving this problem another look and i finally figured out the issue.
Its pretty stupid that i didn't catch it earlier.

In both the `generate_steam_token.py` and `requests.rs` files there is a hardcoded `PLAYER_ID`, this has to be set to your own player id. To get it I just went on the live Rating Update site and got my hex player id from the url.
Convert it into dec and replace the hardcoded values and everything should work.

Also make sure to update the Version to `0.2.9`.

**Comment by hunterloftus** [comment]
Hi @Michiocre 

That worked like a charm! Thank you

**Comment by rnevils** [comment]
@Michiocre I'm using your forked version with the .env updates and still getting the strive token error
```
20:27:51 [DEBUG] (1) reqwest::connect: starting new connection: https://ggst-game.guiltygear.com/
20:27:52 [INFO] Waiting for strive token
20:27:52 [ERROR] Error in received msgpack!  invalid length 1, expected struct Login with 2 elements

20:27:52 [ERROR] Error fetching replays: Couldn't get strive token
```

Were there breaking updates with the strive api recently or am I still missing something?

I'm just trying to do a `cargo run pull`.

Also, what does `VERSION` 0.2.9 correspond to?

**Comment by Michiocre** [comment]
That is the version of the GGST API, and i assume since slayer got release this value has changed
I assume it is going to be 0.2.10 now, but it could be something else.

Edit: According to the error message from the API it should be 0.3.0, but i have not gotten a successful response yet

**Comment by rnevils** [comment]
Working for me now with 0.3.0! Thanks
