### ISSUE TITLE
Character list extends beyond the bottom of the screen

### ISSUE THREAD

**Issue by Spheroman** [halvnykterist/rating-update#56]
On a macbook pro 13, with Arc browser, the character list is long enough that I can't see or click ABA or Slayer.

**Comment by nemasu** [comment]
Is the height of the window as big as it can be?

Also, if you decrease the width enough, it should start using the mobile layout, the character list then becomes scrollable.

**Comment by Spheroman** [comment]
Yeah, the window height matches the height of the screen. Forcing mobile layout does work, but due to the nature of macos and arc browser it's very inconvenient to do so.

**Comment by nemasu** [comment]
Just to make sure, which domain are you using?
Until the original creator has time to update [ratinginfo.info](http://ratingupdate.info/), it's being hosted on [puddle.farm](https://puddle.farm/).

In any case, the character list was getting quite long, so the format has been updated there.

**Comment by Spheroman** [comment]
Yeah, I was on puddle.farm. Looks good now, thank you.
