### ISSUE TITLE
Adding CSS

### ISSUE THREAD

**Issue by henriquezna** [halvnykterist/rating-update#6]
Hi! I saw you were open to someone adding some CSS stylings to the site. I attached some images of some basic stylings using the style.css file. To improve the layout or alignment of the site I'd have to mess with the view templates, but the basic stylings could improve it for now. Colors, etc. can easily be changed. Let me know if you like it.

![top_100](https://user-images.githubusercontent.com/89030483/158656288-748d6bfa-9e0b-4a67-a2d3-8ef47b8e6747.jpg)
![character_popularity](https://user-images.githubusercontent.com/89030483/158656315-aa2eeebb-5180-40eb-926c-f89f7d6b726f.jpg)

**Comment by halvnykterist** [comment]
Some CSS has been added now, but definitely feel free to modify and it with further improvements!
